문제 - 구글 드라이브 파일을 다음 코드를 통해 연동시켜서 진행하려고 했으나 인식이 되지 않음.
from google.colab import drive
drive.mount('/content/drive', force_remount=True) 

![image](https://github.com/Garlic-Ryu/Main_RS/assets/112372749/7be165d6-e790-467a-b3ab-23ea49bd5f8a)
위에서 파일들은 인식하지만
![image](https://github.com/Garlic-Ryu/Main_RS/assets/112372749/c6979407-2f6b-4da6-95a6-2cae87c440db)
여기에서는 찾지 못함


